Added new module ForecastData
ConstAlpha/AlphaForecast pull request #1
Opened 2021-05-08 20:01 UTC by Vagik

2021-05-08 20:03 UTC, Vagik commented on ForecastData/src/main/java/com/ait/forecastdata/IOpenWeather.kt
> +    @GET("data/2.5/onecall?units=metric&exclude=minutely,hourly,alerts&appid=fb5b8d7fc64091a58eb0247d3913b6ae")
Need to discuss, how to hide the appid value

2021-05-10 19:11 UTC, Vagik commented on ForecastData/src/main/java/com/ait/forecastdata/IOpenWeather.kt
> +    @GET("data/2.5/onecall?units=metric&exclude=minutely,hourly,alerts&appid=fb5b8d7fc64091a58eb0247d3913b6ae")
Will be moved to assets

2021-05-12 16:06 UTC, ConstAlpha requested changes

2021-05-12 16:06 UTC, ConstAlpha commented on app/src/main/java/com/ait/alphaforecast/OWAppIdProvider.kt
> +        val bufferReader = application.assets
Mb better to use ```AssetManager```?

2021-05-12 16:06 UTC, ConstAlpha commented on app/src/main/java/com/ait/alphaforecast/MainActivity.kt
> +        lifecycleScope.launch(Dispatchers.Main) {
Please remove this. We don't need any code in our Activity (except of ui setting up)

2021-05-12 16:06 UTC, ConstAlpha commented on data-api/src/main/java/com/ait/dataapi/AppIdProvider.kt
> +package com.ait.dataapi
Use ```com.ait.data.api``` package name here and in other places

2021-05-12 16:06 UTC, ConstAlpha commented on data-api/src/main/java/com/ait/dataapi/AppIdProvider.kt
> +package com.ait.dataapi
And ```com.ait.data.implementation``` in impl module

2021-05-12 16:06 UTC, ConstAlpha commented on data-api/src/main/java/com/ait/dataapi/model/ForecastSource.kt
> +    CHTO_TO_ESHYO
=)

2021-05-12 16:06 UTC, ConstAlpha commented on data-implementation/src/main/java/com/ait/dataimplementation/WeatherForecastManager.kt
> +class WeatherForecastManager(private val appIdProvider: AppIdProvider, private val source: ForecastSource) {
Seems this class should  be renamed to ```WeatherForecastRepository```

2021-05-12 16:06 UTC, ConstAlpha commented on data-implementation/src/main/java/com/ait/dataimplementation/WeatherForecastManager.kt
> +                val client = OkHttpClient().newBuilder()
There must be another class for api building. Just pass ForecastService interface in constructor

2021-05-12 16:06 UTC, ConstAlpha commented on data-implementation/src/main/java/com/ait/dataimplementation/WeatherForecastManager.kt
> +                val client = OkHttpClient().newBuilder()
We must follow single responsibility rule

2021-05-12 16:06 UTC, ConstAlpha commented on app/src/main/java/com/ait/alphaforecast/OWAppIdProvider.kt
> +class OWAppIdProvider(private val application: Application): AppIdProvider {
Please use PascalCase notation here and in other places (rename to ```OwAppIdProvider```)

2021-05-19 17:20 UTC, merged